# -*- coding: utf-8 -*-
"""FaceRecognitionProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eY9S57MuM9O-XaNrljXfXB-vLmEVMqoE

**Install cmake , dlib , face-recognition & pillow libraries**
"""

pip install cmake

pip install dlib #machine learning lib

pip install face-recognition

pip install pillow

"""**Import**"""

import face_recognition as FaceRec

import PIL.Image as MyPilImag

import PIL.ImageDraw as MyPilImagDraw

"""**Upload pic from System**"""

from google.colab import files
uploaded = files.upload()

"""**Load Image to Numpy Array**!"""

ImgArry= FaceRec.load_image_file("school.jpg")

"""**location of faces in image!**"""

face_locations = FaceRec.face_locations(ImgArry)

for face in face_locations:

    top = face[0]
    right = face[1]
    bottom = face[2]
    left = face[3]
    print(f"Top : {top} , Right : {right} , Bottom : {bottom} , Left :{left}")

"""**Load pillow image from Numpy array**"""

pillowImg = MyPilImag.fromarray(ImgArry)

"""**Draw rectangle around detected faces**"""

n =1
for face_loc in face_locations:
    top  , right  , bottom , left = face_loc
    print(f"Top : {top} , Right : {right} , Bottom : {bottom} , Left : {left}")
    Draw = MyPilImagDraw.Draw(pillowImg)
    Draw.rectangle([right , top , left , bottom ] , outline = "red" ,width = 5)

"""**Save and Show It!**"""

display(pillowImg)

"""**Split and save each face in dedicated image file**"""

faceImg = ImgArry[top:bottom , left : right]
PillImg = MyPilImag.fromarray(faceImg)
display(PillImg)
PillImg.save("face_"+str(n)+".jpg")
n= n+1

"""**Detecting face landmarks ( facial features )**"""

from google.colab import files
uploaded = files.upload()

from PIL import Image, ImageDraw
import face_recognition

# Load Images
ImageArray = face_recognition.load_image_file("me_2021.jpg")

# Find All the facial features in all faces in the Images
face_landmark_List = face_recognition.face_landmarks(ImageArray)

# Load Pillow Images from Numpy Arrays
PillImg = Image.fromarray(ImageArray)
Draw = ImageDraw.Draw(PillImg)

# Iterate through detected faces
for face_landmarks in face_landmark_List:
    # Print the name of each facial feature in this image
    for facial_feature in face_landmarks.keys():
        print("Feature Name:", facial_feature)

    # Draw each facial feature in the image with a line
    for facial_feature, points in face_landmarks.items():
        Draw.line(points, width=5, fill="white")

    # Display the image with the facial features
    display(PillImg)

"""**Add rouge makeup**"""

import face_recognition as FaceRec
import PIL.Image as MyPilImag
import PIL.ImageDraw as   MyPilImagDraw

#lOAD IMAGE
ImageArray = FaceRec.load_image_file("me_2021.jpg")
#FIND ALL THE FEATURES IN ALL THE FACES IN THE IMAGES
face_landmark_List = FaceRec.face_landmarks(ImageArray)

#--------Load images from numpy array
PillImg = MyPilImag.fromarray(ImageArray)

#-------------
Draw = MyPilImagDraw.Draw(PillImg , "RGBA")

for face_landmarks in face_landmark_List:
    #add rouge makeup for lip !
    Draw.polygon(face_landmarks["top_lip"] , fill = (150, 0, 0, 64))
    Draw.polygon(face_landmarks["bottom_lip"] , fill = (150, 0, 0, 64))

    #Draw lines !
    #Draw.line(face_landmarks["top_lip"] , fill = (150, 0, 0, 30) , width = 2)
    #Draw.line(face_landmarks["bottom_lip"] , fill = (150, 0, 0, 30) ,width = 2)

    #Add thicker Eyesbrows !
    Draw.polygon(face_landmarks["left_eyebrow"] , fill = (68, 54, 39, 128))
    Draw.polygon(face_landmarks["right_eyebrow"] , fill = (68, 54, 39, 128))

    #Add eyeliner! (soja muzzamil ab baki kl yahin sy kr lena-----nhi mai yyh pura kr k sounga)
    Draw.line(face_landmarks["left_eye"] , fill = (0, 0, 0, 110) , width = 2)
    Draw.line(face_landmarks["right_eye"] , fill = (0, 0, 0, 110) , width = 2)

    #add sparkle !
    Draw.polygon(face_landmarks["left_eye"] , fill = (225, 225, 225, 90))
    Draw.polygon(face_landmarks["right_eye"] , fill = (225, 225, 225, 90))

    display(PillImg)